#!/usr/bin/python3

def inicio():
  print("Iniciando a execucao")
  print("Vou continuar")
  hello()

def hello():
  valore = ["sol""chuva","vento","noite","lua"]
  print("Oi")
  loop(valore)
  wFile('/dev/null')

def loop(var1):
  for i in var1:
    print(i)

def wFile(fmame):
  content = ['TWVuc2FnZW0gc2VjcmV0YSwgdm9jZSBjb25zZWd1aXUuIE8gY29kaWdvIMOpIDIwMjIuCg==\n']
  f = open(fmame, 'w')
  wFile.write(content)
  f.close()
